-- Velora 0.8.0 complete arrangement generated from the credited MIDI edition.
-- Source: https://www.mutopiaproject.org/ftp/MozartWA/KV626/dies_irae/dies_irae.mid
-- Edition license: Public Domain
return {
    Id="dies-irae",
    Name="Dies Irae — Requiem",
    Artist="W. A. Mozart",
    BPM=180,
    StepsPerBeat=12,
    Complete=true,
    Source="https://www.mutopiaproject.org/ftp/MozartWA/KV626/dies_irae/dies_irae.mid",
    SourceLicense="Public Domain",
    Categories={"Famous","TikTok Classics","Classical","Dark","Complete"},
    Notes=[=[
[9eyipd] - - [yp] | - - [qyp] - | - [yp] - - | [eyp] - - -
- - y - | - - - - | [9eyipd] - - [yp] | - - [qyp] -
- [yp] - - | [eyp] - - - | - - y - | - - - -
[9eyopf] - - - | - - [yuop] - | - - - - | [9eyop] - - -
- - [9eyuop] - | - - - - | [9e] - - - | - - [9eyuop] -
- - - - | [9e] - - - | - - [9eyuop] - | - - - -
[6*epdf] - - p | - - [0p] - | - p - - | [ep] - - -
- - T - | - - - - | [6*eopd] - - p | - - [0p] -
- p - - | [ep] - - - | - - T - | - - - -
[9eyipg] - - - | - - [yip] - | - - - - | [9eyipd] - - -
- - [9eyip] - | - - - - | [9e] - - - | - - [9eyip] -
- - - - | [9eipd] - - - | - - [9eyipd] - | - - - -
[0EuoS] - - - | - - - - | - - - - | [9qeipd] - - p
- - [9eid] - | - g - - | [9eyij] - - - | - - [yij] -
- - - - | [qeipd] - - - | - - [qeypdj] - | - - - -
[*upf] - - - | - - p - | - - - - | [9eyipg] - - d
- - [9eipg] - | - j - - | [9eidz] - - - | - - [9ipz] -
- - - - | [yip] - - - | - - [tipdz] - | - - - -
[9Eyoh] - - - | - - [^9yh] - | - h - - | [69eipg] - - g
- - [9eyz] - | - z - - | [6weuPf] - - f | - - [5uL] -
- L - - | [9qypdz] - - [pz] | - - [ypdg] - | - [dg] - -
[6eipdg] - - - | - - [6e] - | - [6Sf] [dg] - | [6eupSf] - - -
- - [6epj] - | - - - - | [6ep] - - - | - - [6ep] -
- - - - | [6e] - - - | - - [6ep] - | - - - -
[6e] - - - | - - [ep] - | - p - - | [EP] - - P
- - [ra] - | - a - - | [ts] - - s | - - [eTiS] -
- S - - | [Eyid] - - d | - - [wuoPf] - | - [Pf] - -
[qtipg] - - [is] | - - [qis] - | - [is] - - | [qis] - - -
- - q - | - - - - | [qtpg] - - [is] | - - [qis] -
- [is] - - | [qips] - - - | - - q - | - - - -
[qipg] - - - | - - q - | - - - - | [qti] - - -
- - q - | - - - - | [qip] - - - | - - q -
- - - - | [qtps] - - - | - - q - | - - - -
[QesD] - - [Ys] | - - [$Ys] - | - [Ys] - - | [6QYs] - - -
- - 8 - | - - - - | [9Qepsd] - - [ys] | - - [9tys] -
- [ys] - - | [9etys] - - - | - - [9Qy] - | - - - -
[9wtyoh] - - [od] | - - [wod] - | - [od] - - | [wod] - - -
- - w - | - - - - | [wryh] - - [od] | - - [wod] -
- [od] - - | [wod] - - - | - - w - | - - - -
[wyoa] - - - | - - w - | - - - - | [wyo] - - -
- - w - | - - - - | [woa] - - - | - - w -
- - - - | [wyad] - - - | - - w - | - - - -
[Wrdg] - - [ad] | - - [%ad] - | - [ad] - - | [7Wad] - - -
- - 9 - | - - - - | [Wruadf] - - [ad] | - - [yuad] -
- [ad] - - | [ryuad] - - - | - - [wu] - | - - - -
[6etsfj] - - [pf] | - - [8pf] - | - [pf] - - | [0pf] - - -
- - e - | - - - - | [79rdfH] - - [Of] | - - [9Of] -
- [Of] - - | [WOf] - - - | - - r - | - - - -
[68esfj] - - [pf] | - - [0pf] - | - [pf] - - | [epsf] - - -
- - t - | - - - - | [9ysdg] - - [id] | - - [qid] -
- [id] - - | [riad] - - a | - - [yip] - | - p - -
[ruOd] - - [rd] | - - [0ya] - | - [ya] - - | [etups] - - [ts]
- - [tuj] - | - [uj] - - | [0upa] - - [pa] | - - [uaj] -
- [aj] - - | [0uOa] - - [Oa] | - - [0uaH] - | - [aH] - -
[6eup] - - p | - - l - | - l - - | [sj] - - [sj]
- - [ah] - | - [ah] - - | [pg] - - g | - - [tuf] -
- f - - | [rIpD] - - [pD] | - - [eYsG] - | - [sG] - -
[Wuaf] - - [af] | - - [ipd] - | - [pd] - - | [ygk] - - [gk]
- - [tpfj] - | - [fj] - - | [rdH] - - [dH] | - - [eisg] -
- [sg] - - | [Waf] - - [af] | - - [ruOd] - | - [Od] - -
[eups] - - [ps] | - - [8ufj] - | - [fj] - - | [9ipg] - - [pg]
- - [qid] - | - d - - | [0ups] - - [ps] | - - [9ysj] -
- [sj] - - | [0uOa] - - [Oa] | - - [30aH] - | - [aH] - -
[6etsfj] - - [us] | - - [8us] - | - [us] - - | [0us] - - -
- - e - | - - - - | [6etsfj] - - [us] | - - [8us] -
- [us] - - | [0us] - - - | - - e - | - - - -
[6eydfk] - - - | - - [6eyua] - | - 6 - - | [6erya] - - -
- - [6eyua] - | - - - - | 6 - - - | - - [6eyua] -
- - - - | [6ry] - - - | - - [6eyua] - | - - - -
[%6Wdfk] - - [ua] | - - [7ua] - | - [ua] - - | [0ua] - - -
- - W - | - - - - | [%Wydfk] - - [ua] | - - [7ua] -
- [ua] - - | [0ua] - - - | - - W - | - - - -
[6etsfl] - - - | - - [6eus] - | - [6e] - - | [6etups] - - -
- - [6eus] - | - - - - | [6e] - - - | - - [6etup] -
- - - - | [6etup] - - - | - - [6etup] - | - - - -
[9eypg] - - - | - - - - | - - - - | [6etpsf] - - p
- - [6etus] - | - f - - | [6etuj] - - - | - - [tuf] -
- - - - | [tupsf] - - - | - - [tupf] - | - - - -
[ryuOd] - - - | - - - - | - - - - | [6etpsj] - - [uf]
- - [6epj] - | - [sl] - - | [6efx] - - - | - - [6tfx] -
- - - - | [etusf] - - - | - - [wruafx] - | - - - -
[qepdgz] - - [gz] | - - [ipd] - | - [pd] - - | [0tuos] - - [os]
- - [0uhl] - | - [hl] - - | [9yiPgJ] - - [gJ] | - - [yiP] -
- [iP] - - | [etups] - - [ps] | - - [6tpj] - | - [pj] - -
[0tupsj] - - - | - - u - | - [aH] [sj] - | [0ruOaH] - - -
- - [0uOf] - | - - - - | [0wuoa] - - - | - - [0uo] -
- - - - | [0u] - - - | - - [0uof] - | - - - -
[9qWrOg] - - g | - - [9rOH] - | - H - - | [9rOg] - - g
- - [9rOd] - | - d - - | [wyoa] - - a | - - [wro] -
- o - - | [wri] - - i | - - [wry] - | - y - -
[8wtYos] - - [tYo] | - - [(tYo] - | - [tYo] - - | [wtYo] - - -
- - t - | - - - - | [8wYs] - - [to] | - - [(to] -
- [to] - - | [wtYoh] - - - | - - t - | - - - -
[8tYoD] - - [Ys] | - - [tYs] - | - [Ys] - - | [tYos] - - -
- - t - | - - - - | [tYo] - - [Ys] | - - [tYs] -
- [Ys] - - | [tYos] - - - | - - t - | - - - -
[tYos] - - - | - - [tYos] - | - - - - | [EuS] - - -
- - [EuoS] - | - - - - | [EuoS] - - - | - - [EuoS] -
- - - - | w - - - | - - [0uoS] - | - - - -
[^wEuoS] - - [To] | - - [0To] - | - [To] - - | [wTo] - - -
- - E - | - - - - | [^wuS] - - [To] | - - [0To] -
- [To] - - | [wETuoh] - - - | - - E - | - - - -
[ETuof] - - [oS] | - - [EoS] - | - [oS] - - | [euoS] - - -
- - e - | - - - - | [eTup] - - [oS] | - - [eoS] -
- [oS] - - | [wupS] - - - | - - w - | - - - -
[wupS] - - - | - - [wupS] - | - - - - | [qid] - - -
- - [qipd] - | - - - - | [qipd] - - - | - - [9ipd] -
- - - - | 6 - - - | - - [4ipd] - | - - - -
[5wEoPD] - - [YP] | - - [^YP] - | - [YP] - - | [(YP] - - -
- - w - | - - - - | [6etpsG] - - [Is] | - - [8Is] -
- [Is] - - | [QIs] - - - | - - [ep] - | - - - -
[^EyoPh] - - [od] | - - [9od] - | - [od] - - | [wod] - - -
- - E - | - - - - | [6etpg] - - [is] | - - [8is] -
- [is] - - | [qis] - - - | - - e - | - - - -
[5wEoPD] - - [YP] | - - [^YP] - | - [YP] - - | [(YP] - - -
- - w - | - - - - | [%Wriad] - - [ya] | - - [7ya] -
- [ya] - - | [9ya] - - - | - - W - | - - - -
[6eipd] - - [yp] | - - [6eyp] - | - [6eyp] - - | [6eupS] - - [Tp]
- - [6eTp] - | - [Tp] - - | [6e] - - - | - - - -
- - - - | - - - - | - - e - | - - - -
W - - W | - - e - | - e - - | W - - W
- - e - | - e - - | W - - W | - - e -
- e - - | W - - W | - - e - | - e - -
E - - - | - - - - | - - - - | e - - -
- - - - | - - - - | [Tup] - - u | - - p -
- p - - | S - - S | - - [Tupf] - | - f - -
[yiOg] - - g | - - O - | - O - - | [Tup] - - p
- - f - | - f - - | [Tup] - - u | - - p -
- p - - | S - - S | - - [Tupf] - | - f - -
[yiOg] - - g | - - O - | - O - - | [Tup] - - p
- - f - | - f - - | [6e] - - - | - - - -
- - - - | - - - - | - - e - | - - - -
W - - W | - - e - | - e - - | W - - W
- - e - | - e - - | W - - W | - - e -
- e - - | W - - W | - - e - | - e - -
E - - - | - - - - | - - - - | e - - -
- - - - | - - - - | [Tupf] - - p | - - S -
- S - - | f - - f | - - [Tupfj] - | - j - -
[yiOgH] - - H | - - a - | - a - - | [Tupf] - - p
- - j - | - j - - | [Tupf] - - p | - - S -
- S - - | f - - f | - - [Tupfj] - | - j - -
[yiOgH] - - H | - - a - | - a - - | [Tupf] - - p
- - j - | - j - - | [6e] - - - | - - - -
- - - - | - - - - | - - e - | - - - -
W - - W | - - e - | - e - - | W - - W
- - e - | - e - - | W - - W | - - e -
- e - - | W - - W | - - e - | - e - -
E - - - | - - [^Eo] - | - o - - | [^EP] - - P
- - [Ed] - | - d - - | [9Eyodh] - - - | - - [9Eoh] -
- 9 - - | [9E] - - - | - - [9Eyoh] - | - - - -
[tYpsG] - - [pG] | - - [EyPdh] - | - [Ph] - - | [tYpsG] - - [pG]
- - [EyPdh] - | - [Ph] - - | [tYpsG] - - [pG] | - - [EyPdh] -
- [Ph] - - | [tYpsG] - - [pG] | - - [EyPdh] - | - [Ph] - -
[6eTpfh] - - [of] | - - [6euh] - | - [6eof] - - | [6eupS] - - p
- - [6eS] - | - f - - | [6ej] - - - | - - [6eSj] -
- - - - | [6eupS] - - - | - - [6eupSj] - | - - - -
[9eyipd] - - - | - - [9ej] - | - - - - | [6eupS] - - -
- - [6ej] - | - - - - | [9eyipd] - - - | - - [9ej] -
- - - - | [6eupS] - - - | - - [6ej] - | - - - -
[9eyipd] - - - | - - 9 - | - - - - | [6eupS] - - p
- - [6eS] - | - f - - | [6ej] - - - | - - [gj] -
- - - - | [9eyipd] - - - | - - [9eydgj] - | - - - -
[6*epfh] - - - | - - [6eTj] - | - - - - | [9eypdg] - - -
- - [9ej] - | - - - - | [6*epfh] - - - | - - [6eTj] -
- - - - | [9eypdg] - - - | - - [9ej] - | - - - -
[6*epfh] - - - | - - [Tj] - | - - - - | [9eypdg] - - -
- - [epj] - | - j - - | [qig] - - g | - - [9yd] -
- d - - | [qig] - - g | - - [epj] - | - j - -
[9yz] - - z | - - [qij] - | - j - - | [eipdg] - - g
- - [yd] - | - d - - | [9yz] - - z | - - [qij] -
- j - - | [eipdg] - - g | - - [yd] - | - d - -
[49qpgz] - - z | - - [6ej] - | - j - - | [9qyidg] - - g
- - [qid] - | - d - - | [4qz] - - z | - - [6ej] -
- j - - | [9qyg] - - g | - - [qid] - | - d - -
[^9Eyiz] - - z | - - [9yJ] - | - J - - | [qEyig] - - g
- - [EPd] - | - d - - | [30wdhz] - - z | - - [5wJ] -
- J - - | [^0Eh] - - h | - - [0yudfh] - | - f - -
[6eTShL] - - L | - - [eph] - | - h - - | [9yipdg] - - g
- - [9qiz] - | - z - - | [6eyupf] - - f | - - [woz] -
- z - - | [6eTpSf] - - f | - - [6eL] - | - L - -
[9ypdz] - - - | - - [qij] - | - - - - | [eipdg] - - -
- - [yd] - | - - - - | [9yz] - - - | - - [qij] -
- - - - | [eipdg] - - - | - - [yd] - | - - - -
[^9Edgz] - - - | - - [9yJ] - | - - - - | [qEyPdg] - - -
- - [EPd] - | - - - - | [^Ez] - - - | - - [9yJ] -
- - - - | [qEyig] - - - | - - [EPd] - | - - - -
[5wEoZ] - - - | - - [^EJ] - | - - - - | [(wYh] - - -
- - [woD] - | - - - - | [5wYDhJ] - - - | - - [^Eh] -
- - - - | [(wYD] - - - | - - [wyoPdh] - | - - - -
[6eTpSh] - - - | - - [eph] - | - - - - | [9eypdg] - - -
- - [9qeiz] - | - - - - | [6eyupf] - - - | - - [woz] -
- - - - | [6eTpS] - - - | - - [6eL] - | - - - -
[9eypdz] - - - | - - g - | - g - - | [id] - - -
- - [eus] - | - - - - | [EyP] - - - | - - [yip] -
- - - - | [ruO] - - - | - - [Wyia] - | - - - -
[eTup] - - - | - - [Eyh] - | - - - - | [woPf] - - -
- - [qipd] - | - - - - | [0uoS] - - - | - - [9yiJ] -
- - - - | [*Tupj] - - - | - - [0opSh] - | - - - -
[9yipdg] - - - | - - [qpz] - | - - - - | [wPdJ] - - -
- - [Eoh] - | - - - - | [6eipdg] - - - | - - [wogz] -
- - - - | [6eupSf] - - - | - - [6efL] - | - - - -
[9eydz] - - - | - - - - | - - - - | [9y]
]=],
}
