-- Velora 0.7.0 complete arrangement generated from the credited MIDI edition.
-- Source: https://www.mutopiaproject.org/ftp/ChopinFF/O66/chopin_fantaisie-impromptu/chopin_fantaisie-impromptu.mid
-- Edition license: Public Domain
return {
    Id="fantaisie-impromptu",
    Name="Fantaisie-Impromptu",
    Artist="Frédéric Chopin",
    BPM=168,
    StepsPerBeat=12,
    Complete=true,
    Source="https://www.mutopiaproject.org/ftp/ChopinFF/O66/chopin_fantaisie-impromptu/chopin_fantaisie-impromptu.mid",
    SourceLicense="Public Domain",
    Categories={"Famous","Classical","Virtuoso","Complete"},
    Notes=[=[
[%W] - - - | - - - - | - - - - | - - - -
- - - - | - - - - | - - - - | - - - -
- - - - | - - - - | - - - - | - - - -
- - - - | - - - - | - - - - | - - - -
- - - - | - - - - | - - - - | - - - -
- - - - | - - - - | - - - - | - - - -
[!*] - - - | W - - - | T - - - | u - - -
T - - - | W - - - | * - - - | W - - -
T - - - | u - - - | T - - - | W - - -
* - - - | W - - - | T - - - | u - - -
T - - - | W - - - | * - - - | W - - -
T - - - | u - - - | T - - - | W - - -
* - - O | W - p - | T O - - | [uo] - - O
T - S - | W f - - | [0D] - - S | W - D -
T S - - | [us] - - S | T - f - | W H - -
* - - O | W - p - | T O - - | [uo] - - O
T - S - | W f - - | [0D] - - S | W - D -
T S - - | [us] - - S | T - f - | W H - -
( - - p | e - S - | T D - - | [IG] - - j
T - L - | e Z - - | [Qn] - - b | T - V -
Y C - - | [px] - - Z | Y - C - | T L - -
[%l] - - Z | ( - j - | Q H - - | [tG] - - j
Q - f - | ( D - - | [%G] - - S | ( - s -
Q D - - | [tp] - - O | Q - a - | ( p - -
* - - O | W - p - | T O - - | [uo] - - O
T - S - | W f - - | [0D] - - S | W - D -
T S - - | [us] - - S | T - f - | W H - -
* - - O | W - P - | E O - - | [uo] - - O
E - S - | W f - - | [0D] - - S | W - D -
E S - - | [Ts] - - S | E - f - | W H - -
[(D] - - f | W - D - | r d - - | [YD] - - k
r - J - | W H - - | [(h] - - x | E - Z -
T L - - | [ok] - - J | T - H - | E h - -
[%J] - - H | ( - k - | W d - - | [rf] - - D
W - H - | ( P - - | [%S] - - a | ( - D -
W o - - | [rP] - - O | W - o - | ( O - -
[6O] - - H | * - s - | Q S - - | [eI] - - G
Q - s - | * S - - | [6i] - - g | * - s -
Q S - - | [eI] - - G | Q - s - | * S - -
[7T] - - S | Q - I - | e p - - | [rY] - - D
e - I - | Q p - - | [3u] - - f | 7 - O -
0 a - - | [WO] - - H | 0 - a - | 7 f - -
[6O] - - H | * - s - | Q S - - | [eI] - - G
Q - s - | * S - - | [6i] - - g | * - s -
Q S - - | [eI] - - G | Q - s - | * S - -
[7i] - - g | Q - a - | e D - - | [rI] - - G
e - a - | Q D - - | [3p] - - j | 7 - a -
0 f - - | [WO] - - H | 0 - a - | 7 f - -
[6O] - - H | * - s - | Q S - - | [eI] - - G
Q - s - | * S - - | [6i] - - g | * - s -
Q S - - | [eI] - - G | Q - s - | * S - -
[7T] - - S | Q - I - | e p - - | [rY] - - D
e - I - | Q p - - | [3u] - - f | 7 - O -
0 a - - | [WO] - - H | 0 - a - | 7 f - -
[6O] - - H | * - s - | Q S - - | [eI] - - G
Q - s - | * S - - | [6D] - - Z | ( - G -
Q j - - | [eS] - - L | Q - G - | ( j - -
[%S] - - L | ( - D - | Q G - - | [ts] - - l
Q - D - | ( G - - | [%s] - - l | ( - D -
Q G - - | [ts] - - l | Q - D - | ( G - -
[6s] - - l | ( - D - | Q G - - | [ra] - - k
Q - D - | ( G - - | [^a] - - k | ( - D -
Q G - - | [EP] - - J | Q - D - | ( G - -
[8P] - - J | ( - D - | Q G - - | [ep] - - j
Q - D - | ( G - - | [8p] - - j | ( - D -
Q G - - | [ep] - - j | Q - D - | ( G - -
[6s] - - l | ( - D - | Q G - - | [ra] - - k
Q - D - | ( G - - | [^a] - - k | ( - D -
Q G - - | [EP] - - J | Q - D - | ( G - -
[7P] - - J | ( - D - | Q G - - | [ep] - - j
Q - D - | ( G - - | [8p] - - j | ( - D -
Q G - - | [WO] - - H | Q - D - | ( G - -
* - - O | W - p - | T O - - | [uo] - - O
T - S - | W f - - | [0D] - - S | W - D -
T S - - | [us] - - S | T - f - | W H - -
* - - O | W - p - | T O - - | [uo] - - O
T - S - | W f - - | [0D] - - S | W - D -
T S - - | [us] - - S | T - f - | W H - -
( - - p | e - S - | T D - - | [IG] - - j
T - L - | e Z - - | [Qn] - - b | T - V -
Y C - - | [px] - - Z | Y - C - | T L - -
[%l] - - Z | ( - j - | Q H - - | [tG] - - j
Q - f - | ( D - - | [%G] - - S | ( - s -
Q D - - | [tp] - - O | Q - a - | ( p - -
* - - O | W - p - | T O - - | [uo] - - O
T - S - | W f - - | [0D] - - S | W - D -
T S - - | [us] - - S | T - f - | W H - -
[Qf] - - D | T - f - | Y D - - | [pd] - - D
Y - G - | T j - - | [WG] - - g | T - G -
i g - - | [af] - - g | i - H - | T L - -
e - - S | T - d - | I S - - | [ps] - - S
I - G - | T j - - | [WG] - - g | T - G -
i g - - | [af] - - g | i - H - | T L - -
[eH] - - G | T - H - | I G - - | [pg] - - G
I - j - | T L - - | [8j] - - H | Q - j -
W H - - | [Yh] - - H | W - l - | Q Z - -
[*H] - - j | W - H - | T h - - | [uH] - - x
T - Z - | W z - - | [(L] - - l | W - k -
t J - - | [Ij] - - H | t - h - | W G - -
[*f] - - G | W - f - | T D - - | [uf] - - x
T - Z - | W z - - | [QL] - - l | T - k -
Y J - - | [pj] - - H | Y - h - | T G - -
[WTuOH] - - - | - - V - | - v - - | C - - c
- - x - | - Z - - | [wTupz] - - L | - - l -
- k - - | J - - j | - - H - | - h - -
G - - g | - - f - | - D - - | d - - S
- - s - | - a - - | P - - p | - - O -
- o - - | I - - u | - - Y - | - T - -
[%W] - - - | - - - - | - - - - | [ufb] - - V
- - x - | - x - - | [TSC] - - x | - - L -
- L - - | [WOZ] - - L | - - V - | - H - -
[0uj] - - H | - - x - | - f - - | [*TG] - - f
- - L - | - S - - | [%WD] - - S | - - H -
- O - - | [30p] - - O | - - f - | - u - -
[!*I] - - u | - - S - | - T - - | [%Y] - - T
- - O - | - W - - | [%Y] - - T | - - O -
- W - - | [6Y] - - T | - - p - | - e - -
[%Y] - - T | - - O - | - W - - | [5Y] - - T
- - o - | - w - - | [%Y] - - T | - - O -
- W - - | Y - - t | - - O - | - W - -
! - - - | % - - - | * - - - | q - - -
W - - - | T - - - | i - - - | T - - -
W - - - | q - - - | * - - - | % - - -
! - - - | % - - - | * - - - | q - - -
W - - - | T - - - | i - - - | T - - -
W - - - | q - - - | * - - - | % - - -
[!O] - - - | W - - - | t - - - | Y - - -
t - - - | W - - - | [*P] - - - | W - O -
t - - - | [IS] - - - | t - D - | W - - -
[*g] - - - | W - - - | T - - - | i - - -
T - - - | W - - - | [*H] - - - | W - - -
i - - - | O - - - | i - - - | W - - -
[IG] - - - | Y - - - | W - - - | [ig] - - -
T - - - | W - - - | [YD] - - - | t - - -
W - - - | [Tg] - - - | W - - - | q S - -
[%O] - - - | ( - - - | W - - - | t - - -
W - - - | ( - - - | [$P] - - - | Q - - -
E - - - | T - - - | E - - - | Q - - -
^ - - - | q - - - | E - - - | y - - -
E - - - | q - - - | [^a] - - - | E - P -
y - - - | [OD] - - - | y - g - | E - - -
[(G] - - - | I - - - | E - - - | [qg] - - -
i - - - | e - - - | [QD] - - - | Y - - -
E - - - | [Wg] - - - | I - - - | t - - -
[*S] - - - | W - - - | T - - - | i - - -
T - - - | W - - [sSD] | [(Sg] - - - | w - - -
T - - - | Y - - - | T - D - | w - - -
[%D] - - - | ( - - - | W - - - | t - - -
W - - - | ( - - - | % - - - | ( - - -
Q - - - | E - - - | Q - - - | ( - - -
[%O] - - - | ( - - - | W - - - | t - - -
W - - - | ( - - - | [%P] - - - | W - O -
t - - - | [IS] - - - | t - D - | W - - -
[*g] - - - | W - - - | T - - - | i - - -
T - - - | W - - - | [*H] - - - | W - - -
i - - - | O - - - | i - - - | W - - -
[IG] - - - | Y - - - | W - - - | [ig] - - -
T - - - | W - - - | [YD] - - - | t - - -
W g D [SD] | [Tg] - - - | W - - - | q S - -
[%O] - - - | ( - - - | W - - - | t - - -
W - - - | ( - - - | [$P] - - - | Q - - -
E - - - | T - - - | E - - - | Q - - -
^ - - - | q - - - | E - - - | y - - -
E - - - | q - - - | [^a] - - - | E - P -
y - - - | [OD] - - - | y - g - | E - - -
[(G] - - - | I - - - | E - - - | [qg] - - -
i - - - | e - - - | [QD] - - - | Y - - -
E - - - | [Wg] - - - | I - - - | t - - -
[*S] - - - | W - - - | T - - - | i - - -
T - o - | [WO] P O - | [*g] - - - | W - - -
t - - - | I - - - | t - D - | W - - -
[*D] - - - | W - - - | t - - - | I - - -
t - - - | W - - - | [*S] - - - | W - - -
T - - - | i - - - | T - H - | W - - -
[%O] - - - | ( - - - | W - - - | t - - -
W - - - | ( - - - | [%P] - - - | ( - - -
w p - - | [TP] - - - | w - - - | ( s - -
[%O] - - - | ( - - - | W - - - | [tl] - - -
W - - - | ( - - - | * - - J | W - - H
T - f - | u - S - | T P - - | W - H -
[@Y] - - - | ( - - - | W - - - | t - - -
W - - - | ( - - s | [@P] - - - | ( - - -
w p - - | [TP] - - - | w - - - | ( D - -
[%O] - - - | ( - - - | W - - - | t - - -
W - - - | ( - - - | [$P] - - - | Q - - -
E - - - | [TS] - - - | [Es] - - - | [QP] - - -
[%O] - - - | W - - - | t - - - | Y - - -
t - - - | W - - - | [(P] - - - | W - O -
t - - - | [IS] - - - | t - D - | W - - -
[*g] - - - | W - - - | T - - - | i - - -
T - - - | W - - - | [*H] - - - | W - - -
i - - - | O - - - | i - - - | W - - -
[IG] - - - | Y - - - | W - - - | [ig] - - -
T - - - | W - - - | [YD] - - - | t - - -
W g D [SD] | [Tg] - - - | W - - - | q S - -
[%O] - - - | ( - - - | W - - - | t - - -
W - - - | ( - - - | [$P] - - - | Q - - -
E - - - | T - - - | E - - - | Q - - -
^ - - - | q - - - | E - - - | y - - -
E - - - | q - - - | [^a] - - - | E - P -
y - - - | [OD] - - - | y - g - | E - - -
[(G] - - - | I - - - | E - - - | [qg] - - -
i - - - | e - - - | [QD] - - - | Y - - -
E - - - | [Wg] - - - | I - - - | t - - -
[*S] - - - | W - - - | T - - - | i - - -
T - o - | [WO] P O - | [*g] - - - | W - - -
t - - - | I - - - | t - D - | W - - -
[*D] - - - | W - - - | t - - - | I - - -
t - - - | W - - - | [*S] - - - | W - - -
T - - - | i - - - | T - H - | W - - -
[%O] - - - | ( - - - | W - - - | t - - -
W - - - | ( - - - | [%P] - - - | ( - - -
w p - - | [TP] - - - | w - - - | ( s - -
[%O] - - - | ( - - - | W - - - | [tl] - - -
W - - - | ( - - - | * - - J | W - - H
T - f - | u - S - | T P - - | W - H -
[@Y] - - - | ( - - - | W - - - | t - - -
W - - - | ( - - s | [@P] - - - | ( - - -
w p - - | [TP] - - - | w - - - | ( D - -
[%O] - - - | ( - - - | W - - - | t - - -
W - - - | ( - - - | [$P] - - - | Q - - -
E - - - | [TS] - - - | [Es] - - - | [QP] - - -
[%O] - - - | ( - - - | W - - - | t - - -
W - - - | ( - - - | [%P] - - - | W - O -
t - - - | [IS] - - - | t - D - | W - - -
[*g] - - - | W - - - | T - - - | i - - -
T - - - | W - - - | [*H] - - - | W - - -
i - - - | O - - - | i - - - | W - - -
[IG] - - - | Y - - - | W - - - | [ig] - - -
T - - - | W - - - | [YD] - - - | t - - -
W g D [SD] | [Tg] - - - | W - - - | q S - -
[%O] - - - | ( - - - | W - - - | t - - -
W - - - | ( - - - | [$P] - - - | Q - - -
E - - - | T - - - | E - - - | Q - - -
^ - - - | q - - - | E - - - | y - - -
E - - - | q - - - | [^a] - - - | E - P -
y - - - | [OD] - - - | y - g - | E - - -
[(G] - - - | I - - - | E - - - | [qg] - - -
i - - - | e - - - | [QD] - - - | Y - - -
E - - - | [Wg] - - - | I - - - | t - - -
[*S] - - - | W - - - | T - - - | i - - -
T - o - | [WO] P O - | [*g] - - - | W - - -
t - - - | I - - - | t - D - | W - - -
[*D] - - - | W - - - | t - - - | I - - -
t - - - | W - - - | * - - - | W - - -
t - - - | I - - - | t - - - | W - - -
* - - O | W - p - | T O - - | [uo] - - O
T - S - | W f - - | [0D] - - S | W - D -
T S - - | [us] - - S | T - f - | W H - -
* - - O | W - p - | T O - - | [uo] - - O
T - S - | W f - - | [0D] - - S | W - D -
T S - - | [us] - - S | T - f - | W H - -
( - - p | e - S - | T D - - | [IG] - - j
T - L - | e Z - - | [Qn] - - b | T - V -
Y C - - | [px] - - Z | Y - C - | T L - -
[%l] - - Z | ( - j - | Q H - - | [tG] - - j
Q - f - | ( D - - | [%G] - - S | ( - s -
Q D - - | [tp] - - O | Q - a - | ( p - -
* - - O | W - p - | T O - - | [uo] - - O
T - S - | W f - - | [0D] - - S | W - D -
T S - - | [us] - - S | T - f - | W H - -
* - - O | W - P - | E O - - | [uo] - - O
E - S - | W f - - | [0D] - - S | W - D -
E S - - | [Ts] - - S | E - f - | W H - -
[(D] - - f | W - D - | r d - - | [YD] - - k
r - J - | W H - - | [(h] - - x | E - Z -
T L - - | [ok] - - J | T - H - | E h - -
[%J] - - H | ( - k - | W d - - | [rf] - - D
W - H - | ( P - - | [%S] - - a | ( - D -
W o - - | [rP] - - O | W - o - | ( O - -
[6O] - - H | * - s - | Q S - - | [eI] - - G
Q - s - | * S - - | [6i] - - g | * - s -
Q S - - | [eI] - - G | Q - s - | * S - -
[7T] - - S | Q - I - | e p - - | [rY] - - D
e - I - | Q p - - | [3u] - - f | 7 - O -
0 a - - | [WO] - - H | 0 - a - | 7 f - -
[6O] - - H | * - s - | Q S - - | [eI] - - G
Q - s - | * S - - | [6i] - - g | * - s -
Q S - - | [eI] - - G | Q - s - | * S - -
[7i] - - g | Q - a - | e D - - | [rI] - - G
e - a - | Q D - - | [3p] - - j | 7 - a -
0 f - - | [WO] - - H | 0 - a - | 7 f - -
[6O] - - H | * - s - | Q S - - | [eI] - - G
Q - s - | * S - - | [6i] - - g | * - s -
Q S - - | [eI] - - G | Q - s - | * S - -
[7T] - - S | Q - I - | e p - - | [rY] - - D
e - I - | Q p - - | [3u] - - f | 7 - O -
0 a - - | [WO] - - H | 0 - a - | 7 f - -
[6O] - - H | * - s - | Q S - - | [eI] - - G
Q - s - | * S - - | [6D] - - Z | ( - G -
Q j - - | [eS] - - L | Q - G - | ( j - -
[%S] - - L | ( - D - | Q G - - | [ts] - - l
Q - D - | ( G - - | [%s] - - l | ( - D -
Q G - - | [ts] - - l | Q - D - | ( G - -
[6s] - - l | ( - D - | Q G - - | [ra] - - k
Q - D - | ( G - - | [^a] - - k | ( - D -
Q G - - | [EP] - - J | Q - D - | ( G - -
[8P] - - J | ( - D - | Q G - - | [ep] - - j
Q - D - | ( G - - | [8p] - - j | ( - D -
Q G - - | [ep] - - j | Q - D - | ( G - -
[6s] - - l | ( - D - | Q G - - | [ra] - - k
Q - D - | ( G - - | [^a] - - k | ( - D -
Q G - - | [EP] - - J | Q - D - | ( G - -
[7P] - - J | ( - D - | Q G - - | [ep] - - j
Q - D - | ( G - - | [8p] - - j | ( - D -
Q G - - | [WO] - - H | Q - D - | ( G - -
* - - O | W - p - | T O - - | [uo] - - O
T - S - | W f - - | [0D] - - S | W - D -
T S - - | [us] - - S | T - f - | W H - -
* - - O | W - p - | T O - - | [uo] - - O
T - S - | W f - - | [0D] - - S | W - D -
T S - - | [us] - - S | T - f - | W H - -
( - - p | e - S - | T D - - | [IG] - - j
T - L - | e Z - - | [Qn] - - b | T - V -
Y C - - | [px] - - Z | Y - C - | T L - -
[%l] - - Z | ( - j - | Q H - - | [tG] - - j
Q - f - | ( D - - | [%G] - - S | ( - s -
Q D - - | [tp] - - O | Q - a - | ( p - -
* - - O | W - p - | T O - - | [uo] - - O
T - S - | W f - - | [0D] - - S | W - D -
T S - - | [us] - - S | T - f - | W H - -
[Qf] - - D | T - f - | Y D - - | [pd] - - D
Y - G - | T j - - | [WG] - - g | T - G -
i g - - | [af] - - g | i - H - | T L - -
e - - S | T - d - | I S - - | [ps] - - S
I - G - | T j - - | [WG] - - g | T - G -
i g - - | [af] - - g | i - H - | T L - -
[eH] - - G | T - H - | I G - - | [pg] - - G
I - j - | T L - - | [8j] - - H | Q - j -
W H - - | [Yh] - - H | W - l - | Q Z - -
[*H] - - j | W - H - | T h - - | [uH] - - x
T - Z - | W z - - | [(L] - - l | W - k -
t J - - | [Ij] - - H | t - h - | W G - -
[*f] - - G | W - f - | T D - - | [uf] - - x
T - Z - | W z - - | [QL] - - l | T - k -
Y J - - | [pj] - - H | Y - h - | T G - -
[WTuOH] - - - | - - V - | - v - - | C - - c
- - x - | - Z - - | [wTupz] - - L | - - l -
- k - - | J - - j | - - H - | - h - -
G - - g | - - f - | - D - - | d - - S
- - s - | - a - - | P - - p | - - O -
- o - - | I - - u | - - Y - | - T - -
[%W] - - - | - - - - | - - - - | [ufb] - - V
- - x - | - x - - | [TSC] - - x | - - L -
- L - - | [WOZ] - - L | - - V - | - H - -
[0uj] - - H | - - x - | - f - - | [*TG] - - f
- - L - | - S - - | [%WD] - - S | - - H -
- O - - | [30p] - - O | - - f - | - u - -
[!*I] - - u | - - S - | - T - - | [%Y] - - T
- - O - | - W - - | [%Y] - - T | - - O -
- W - - | [6Y] - - T | - - p - | - e - -
[%Y] - - T | - - O - | - W - - | [5Y] - - T
- - o - | - w - - | [%Y] - - T | - - O -
- W - - | Y - - t | - - O - | - W - -
[!Y] - - T | - - [0O] - | - W - - | [*p] - - O
- - [%f] - | - u - - | [!p] - - O | - - [Qf] -
- u - - | [8p] - - O | - - [%D] - | - Y - -
[!p] - - O | - - [0D] - | - Y - - | [*p] - - O
- - [%S] - | - T - - | [!u] - - Y | - - [QO] -
- W - - | [8u] - - Y | - - [%O] - | - W - -
[!Y] - - T | - - [0O] - | - W - - | [*p] - - O
- - [%f] - | - u - - | [!p] - - O | - - [Qf] -
- u - - | [8p] - - O | - - [%D] - | - Y - -
[!p] - - O | - - [0D] - | - Y - - | [*p] - - O
- - [%S] - | - T - - | [!u] - - Y | - - [QO] -
- W - - | [8u] - - Y | - - [%O] - | - W - -
[!Y] - - T | - - [0O] - | - W - - | [*p] - - O
- - [%f] - | - u - - | [!I] - - u | - - [WS] -
- T - - | [*p] - - O | - - [%f] - | - u - -
[!Y] - - T | - - [0O] - | - W - - | [*p] - - O
- - [%f] - | - u - - | [!I] - - u | - - [WS] -
- T - - | [*p] - - O | - - [%f] - | - u - -
[!I] - - u | - - [0S] - | - T - - | [*p] - - O
- - [%S] - | - T - - | [!I] - - u | - - [0S] -
- T - - | [*p] - - O | - - [%S] - | - T - -
[!I] - - u | - - [0S] - | - T - - | [*p] - - O
- - [%S] - | - T - - | [!I] - - u | - - [0S] -
- T - - | [*p] - - O | - - [%S] - | - T - -
[!Y] - - T | - - O - | - W - - | Y - - T
- - O - | - W - - | Y - - T | - - O -
- W - - | Y - - T | - - O - | - W - -
Y - - T | - - O - | - W - - | Y - - T
- - O - | - W - - | Y - - T | - - O -
- W - - | Y - - T | - - O - | - W - -
[!%Y] - - T | - - O - | - W - - | Y - - T
- - O - | - W - - | Y - - T | - - O -
- W - - | Y - - T | - - O - | - W - -
[^Y] - - T | - - O - | - W - - | [%Y] - - T
- - O - | - W - - | [*Y] - - T | - - O -
- W - - | [(Y] - - T | - - O - | - W - -
[qY] - - T | - - O - | - W - - | Y - - T
- - O - | - W - - | Y - - T | - - O -
- W - - | Y - - T | - - O - | - W - -
[WY] - - T | - - O - | - W - - | Y - - T
- - O - | - W - - | Y - - T | - - O -
- W - - | Y - - T | - - O - | - W - -
[QY] - - T | - - O - | - W - - | Y - - T
- - O - | - W - - | [qY] - - T | - - O -
- W - - | Y - - T | - - O - | - W - -
[(Y] - - T | - - O - | - W - - | Y - - T
- - O - | - W - - | [qY] - - T | - - O -
- W - - | [*Y] - - T | - - O - | - W - -
[%Y] - - T | - - O - | - q - - | Y - - T
- - O - | - q - - | Y - - T | - - O -
- q - - | Y - - T | - - O - | - q - -
[%i] - - Y | - - O - | - W - - | i - - Y
- - O - | - W - - | i - - Y | - - O -
- W - - | i - - Y | - - O - | - W - -
[!%QWtY] - - - | - - - - | - - - - | - - - -
- - - - | - - - - | - - - - | - - - -
- - - - | - - - - | - - - - | - - - -
[!%qT]
]=],
}
